[package]
name = "modor_internal"
description = "Internal module of Modor game engine for common utils"
readme = "./README.md"
keywords = ["modor", "internal"]
categories = ["game-engines"]
exclude = [".github", "README.md"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"
repository = "https://github.com/modor-engine/modor"
rust-version.workspace = true

[dependencies]
typed-index-collections.workspace = true
