[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2021-0127" # serde_cbor is used by criterion
]

[bans]
multiple-versions = "deny"
skip = [
    { name = "cfg-if", version = "0.1.10" },
    { name = "core-foundation", version = "0.7.0" },
    { name = "core-foundation-sys", version = "0.7.0" },
    { name = "core-graphics", version = "0.19.2" },
    { name = "wasi", version = "0.10.2+wasi-snapshot-preview1" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[licenses]
unlicensed = "deny"
copyleft = "deny"
default = "deny"
allow = ["Apache-2.0", "BSD-3-Clause", "CC0-1.0", "ISC", "MIT", "Zlib"]
