[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2021-0127" # serde_cbor is used by criterion
]

[bans]
multiple-versions = "deny"
skip = [
    { name = "itoa", version = "0.4" }, # criterion uses an older version of itoa
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[licenses]
unlicensed = "deny"
copyleft = "deny"
default = "deny"
allow = ["MIT", "Apache-2.0"]
