[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2021-0127" # serde_cbor is used by criterion and has not yet been updated
]

[bans]
multiple-versions = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[licenses]
unlicensed = "deny"
copyleft = "deny"
default = "deny"
allow = ["MIT", "Apache-2.0"]
