[package]
name = "modor_graphics"
version = "0.1.0"
authors = ["Nicolas Ferré <nicolas.ferre.public@gmail.com>"]
edition = "2021"
description = "Graphics module of Modor game engine"
license = "MIT OR Apache-2.0"
repository = "https://github.com/modor-engine/modor"
readme = "./README.md"
keywords = ["modor", "graphics", "display", "rendering", "game"]
categories = ["game-engines"]
exclude = [".github", "README.md", "assets"]

[dependencies]
bytemuck = { version = "1.8", features = ["derive"] }
fxhash = "0.2"
futures = "0.3"
image = "0.24"
instant = "0.1"
log = "0.4"
spin_sleep = "1.1.1"
typed-index-collections = "3.0"
winit = "0.27"
modor = { version = "0.1.0", path = "../modor" }
modor_input = { version = "0.1.0", path = "../modor_input" }
modor_internal = { version = "0.1.0", path = "../modor_internal" }
modor_jobs = { version = "0.1.0", path = "../modor_jobs" }
modor_math = { version = "0.1.0", path = "../modor_math" }
modor_physics = { version = "0.1.0", path = "../modor_physics" }

[target.'cfg(not(target_os = "android"))'.dependencies]
gilrs = "0.9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = "0.14"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "0.3"
wgpu = { version = "0.14", features = ["webgl"] }

[dev-dependencies]
approx = "0.5"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"
