[package]
name = "modor"
version = "0.1.0"
authors = ["Nicolas Ferré <nicolas.ferre.public@gmail.com>"]
edition = "2021"
description = "Core library of Modor game engine"
license = "MIT OR Apache-2.0"
repository = "https://github.com/modor-engine/modor"
readme = "../../README.md"
keywords = ["game", "engine", "modular", "object", "framework"]
categories = ["game-engines"]
exclude = [".github", "README.md"]

[dependencies]
fxhash = "0.2"
scoped_threadpool = "0.1"
typed-index-collections = "3.0"
modor_derive = { version = "0.1.0", path = "../modor_derive" }
modor_internal = { version = "0.1.0", path = "../modor_internal" }

[dev-dependencies]
criterion = "0.3"
doc-comment = "0.3"
static_assertions = "1.1"
instant = "0.1"
spin_sleep = "1.1"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
compiletest_rs = "0.9"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[[bench]]
name = "entity_creation"
harness = false

[[bench]]
name = "simple_system_iteration"
harness = false

[[bench]]
name = "one_system_fragmented_iteration"
harness = false

[[bench]]
name = "multiple_systems_fragmented_iteration"
harness = false

[[bench]]
name = "parallel_system_iteration"
harness = false
